// Copyright (c) 2020 gyselroth GmbH

#ifndef SRC_DOCXBOX_CONFIG_H_
#define SRC_DOCXBOX_CONFIG_H_

#define DOCXBOX_VERSION_MAJOR "0"
#define DOCXBOX_VERSION_MINOR "0"
#define DOCXBOX_VERSION_PATCH "1"

#endif // SRC_DOCXBOX_CONFIG_H_
